dependencies/tachyon-bp-fw/build/artifacts/qup/qupv3fw.elf /lib/firmware/updates
dependencies/tachyon-bp-fw/build/artifacts/adsp/adsp.* /lib/firmware/updates/tachyon

dependencies/tachyon-ubuntu-20.04/na/firmware/yupik_ipa_fws.* /lib/firmware/updates/tachyon
dependencies/tachyon-ubuntu-20.04/na/firmware/CAMERA_ICP* /lib/firmware/updates
dependencies/tachyon-ubuntu-20.04/na/firmware/a660* /lib/firmware/updates
dependencies/tachyon-ubuntu-20.04/na/firmware/ipa /lib/firmware/updates
dependencies/tachyon-ubuntu-20.04/na/firmware/ipa_fws.* /lib/firmware/updates
dependencies/tachyon-ubuntu-20.04/na/firmware/vpu* /lib/firmware/updates
